issue/41 - Bump WordPress minimum requirements
awesomemotive/affiliatewp-affiliate-area-shortcodes pull request #42
Opened 2021-10-28 14:43 UTC by dbeja

Issue #41 

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

## How to test it
1. Install and activate Affiliate Area Shortcodes add-on
2. Confirm the plugin works as expected without any PHP errors.
3. Create a new page with the shortcode: `[affiliate_area]` and confirm the page shows the affiliate area

2021-10-30 21:53 UTC, DrewAPicture requested changes
Found one issue with the file path for the requirements check superclass.

2021-10-30 21:53 UTC, DrewAPicture commented on affiliatewp-affiliate-area-shortcodes.php
> +	require_once dirname( __FILE__ ) . '/includes/lib/affwp/class-affiliatewp-requirements-check_v1_1.php';
Looks like the file path is incorrect. Should be hyphens instead of underscores.

```suggestion
	require_once dirname( __FILE__ ) . '/includes/lib/affwp/class-affiliatewp-requirements-check-v1-1.php';
```

2021-10-30 21:56 UTC, DrewAPicture requested changes
Also as this is a free add-on, we need to update the "Requires at least" header and changelog in the readme.txt to 5.2.

2021-11-01 08:49 UTC, dbeja commented
Shouldn't the changelog be updated only at the release PR?

2021-11-02 11:39 UTC, DrewAPicture approved these changes
Looks good.

2021-11-02 12:48 UTC, merged