Issue/48 - Fixed banner message not showing when AffiliateWP is not installed
awesomemotive/affiliatewp-affiliate-area-shortcodes pull request #49
Opened 2023-01-03 20:38 UTC by darvinsilveira-am

Issue #48 

Steps to test:

1) Install Affiliate Shortcodes add-on;

You should see a banner message like the image below telling you that the add-on requires AffiliateWP:

![image](https://user-images.githubusercontent.com/116665983/210437199-6f377e90-b2f5-434a-8b20-d47f34ca24ce.png)

(Observation: the message changes if the AffiliateWP is listed as a plugin or not)

2) Now install AffiliateWP, the message should go away.

![image](https://user-images.githubusercontent.com/116665983/210437445-c1b94d90-a7e3-4826-a87f-2a8099918a6b.png)

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

2023-01-04 00:08 UTC, amdrew commented
Looking good so far

## ✅ Notice shows when AffiliateWP is not activated

![image](https://user-images.githubusercontent.com/52581/210446252-f949b5d2-096a-4d82-9658-5c1609201270.png)

## ✅ Notice disappears once AffiliateWP is activated

![image](https://user-images.githubusercontent.com/52581/210446351-8cbcec30-167c-47fb-a417-46f5d10cc3f8.png)

## ✅ Using an AffiliateWP version less than 2.6  shows inline minimum requirements notice

![image](https://user-images.githubusercontent.com/52581/210460993-2d6e6796-d323-4f35-a5fe-678f5f686b19.png)

2023-01-04 00:12 UTC, amdrew requested changes
We'll need to update this [doc URL](https://github.com/awesomemotive/affiliatewp-affiliate-area-shortcodes/blob/master/affiliatewp-affiliate-area-shortcodes.php#L163)  to `https://affiliatewp.com/docs/minimum-requirements-roadmap/`

2023-01-04 00:17 UTC, amdrew commented
As per the [requirements](https://affiliatewp.com/docs/minimum-requirements-roadmap/) for "All Other Official Free & Pro Add-ons" we'll need to also change the minimum version of PHP to 7.4 (It says 7.0 on the table but I believe we decided on 7.4) for this addon here: https://github.com/awesomemotive/affiliatewp-affiliate-area-shortcodes/blob/issue/48/includes/lib/affwp/class-affiliatewp-requirements-check-v1-1.php#L60

2023-01-04 00:23 UTC, amdrew commented on affiliatewp-affiliate-area-shortcodes.php
>  			$affwp_version = get_option( 'affwp_version' );
`$affwp_version` is no longer being used here.

2023-01-04 00:26 UTC, amdrew commented
@darvinsilveira Just some small changes listed above 👍

2023-01-04 09:05 UTC, darvinsilveira-am commented on affiliatewp-affiliate-area-shortcodes.php
>  			$affwp_version = get_option( 'affwp_version' );
Well noted

2023-01-04 09:13 UTC, darvinsilveira-am commented
@amdrew all fixed 👍

2023-01-05 03:11 UTC, amdrew approved these changes

2023-01-05 03:13 UTC, amdrew commented
I'm going to merge this in for further testing. Thanks @darvinsilveira!

2023-01-05 03:13 UTC, merged